services:
  mysql:
    image: mysql:8.4
    container_name: system-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: matkhau0107
      MYSQL_DATABASE: system
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pmatkhau0107"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  mysql_data:
